name: Events demo 1
on: 
  push: 
    branches:
      - "main"
jobs:
  if_merged:
    runs-on: ubuntu-latest
    steps:
      - name: Pull request merged
        run: echo "The PR was merged"
      - name: Get Code
        uses: actions/checkout@v3 
      - name: Install depencies
        run: npm ci 
      - name: Build code 
        run: npm run build 
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with: 
          name: dist-files
          path: dist
      - name: Deploy project 
        run: echo "Deploying ... "
      - name: Output even data
        run: echo "${{toJSON(github.event)}}"
      